### PR TITLE
Created ImageCreatorView

### PR DESCRIPTION
**Pull request by matheweon**

### CODE REVIEW

**Comment by matheweon** [comment]
Are you aware that on the main branch, the redeclaration of the `Guess` struct in RankingGuessesView and WaitingForRankingView is causing an error?

**Comment by matheweon** [comment]
I'll run these after this is PR is merged
`git push origin --delete 6-create-image-creator-view`
`git branch -D 6-create-image-creator-view`

**Comment by atlant04** [comment]
yeah, someone might have declared the `Guess` struct twice, I think #29 gets rid of the duplication though. Also, when you merge, it will ask you to automatically delete the branch, so no need to do it automatically, unless you prefer to of course.

**Comment by matheweon** [comment]
> Also, when you merge, it will ask you to automatically delete the branch, so no need to do it automatically, unless you prefer to of course.

After this PR merges, I'll be deleting the old `6-create-image-creator-view` branch from my previous PR, not the new `6-image-creator-view` branch associated with this PR.

**Comment by atlant04** [comment]
Oh I see, you closed the other one. Makes sense

**Review by atlant04 — APPROVED** [review]
Looks good, great work!

**Pull request merged**
